name: mindtamer
description: MindTamer – pixel-style mental health companion with gamified loop (Flutter + Flame)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  in_app_purchase: ^3.2.0
  flame: ^1.14.0
  csv: ^6.0.0
  archive: ^3.6.1
  path_provider: ^2.1.3
  share_plus: ^10.0.2
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.1+2
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    # Explicitly include tab icons to ensure bundling
    - assets/images/icons/tab_home_32.png
    - assets/images/icons/tab_mood_32.png
    - assets/images/icons/tab_journal_32.png
    - assets/images/icons/tab_meds_32.png
    - assets/images/icons/tab_settings_32.png
  fonts:
    - family: PixelFont
      fonts:
        - asset: assets/fonts/PlaceholderPixelFont.ttf
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
